// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUserInfo() {
  return window['go']['main']['App']['GetUserInfo']();
}

export function Getlogin() {
  return window['go']['main']['App']['Getlogin']();
}

export function GetloginStatus() {
  return window['go']['main']['App']['GetloginStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Onstop(arg1) {
  return window['go']['main']['App']['Onstop'](arg1);
}

export function ReadConfig() {
  return window['go']['main']['App']['ReadConfig']();
}

export function Stopwork() {
  return window['go']['main']['App']['Stopwork']();
}

export function Stopwork1() {
  return window['go']['main']['App']['Stopwork1']();
}

export function Userlogin() {
  return window['go']['main']['App']['Userlogin']();
}

export function WriteConfig(arg1) {
  return window['go']['main']['App']['WriteConfig'](arg1);
}
