// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Getlogin() {
  return window['go']['main']['App']['Getlogin']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Stopwork() {
  return window['go']['main']['App']['Stopwork']();
}

export function Userlogin() {
  return window['go']['main']['App']['Userlogin']();
}
