// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function Getlogin():Promise<boolean>;

export function Greet(arg1:string):Promise<string>;

export function Stopwork():Promise<void>;

export function Userlogin():Promise<types.LoginUrl>;
