// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function GetUpdateUpgrader() {
  return window['go']['main']['App']['GetUpdateUpgrader']();
}

export function GetUserInfo() {
  return window['go']['main']['App']['GetUserInfo']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Getlogin() {
  return window['go']['main']['App']['Getlogin']();
}

export function GetloginStatus() {
  return window['go']['main']['App']['GetloginStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Onstop() {
  return window['go']['main']['App']['Onstop']();
}

export function ReadConfig() {
  return window['go']['main']['App']['ReadConfig']();
}

export function Stopwork() {
  return window['go']['main']['App']['Stopwork']();
}

export function Userlogin() {
  return window['go']['main']['App']['Userlogin']();
}

export function WriteConfig(arg1) {
  return window['go']['main']['App']['WriteConfig'](arg1);
}
