// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';
import {main} from '../models';

export function GetUserInfo():Promise<types.UserinfoLite>;

export function Getlogin():Promise<number>;

export function GetloginStatus():Promise<boolean>;

export function Greet(arg1:string):Promise<string>;

export function Onstop(arg1:context.Context):Promise<boolean>;

export function ReadConfig():Promise<main.ConfigResponse>;

export function Stopwork():Promise<void>;

export function Stopwork1():Promise<void>;

export function Userlogin():Promise<types.LoginUrl>;

export function WriteConfig(arg1:string):Promise<main.ConfigResponse>;
