// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Bili_danmaku_Start(arg1:context.Context):Promise<void>;

export function Monitor():Promise<boolean>;

export function Start():Promise<boolean>;

export function Stop():Promise<boolean>;
