// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bili_danmaku_Start(arg1) {
  return window['go']['main']['Program']['Bili_danmaku_Start'](arg1);
}

export function Monitor() {
  return window['go']['main']['Program']['Monitor']();
}

export function Start() {
  return window['go']['main']['Program']['Start']();
}

export function Stop() {
  return window['go']['main']['Program']['Stop']();
}
